#!/usr/env/bin python 
import rospy 
from smach_ros import SimpleActionState
from mini_golf.srv import CV_POIs, CV_POIsResponse

class GamePlanner(object):
	def __init__(self):
		#perform subscriptiosn

		#establish publishers

		#establish service proxies 
		self.get_POIs = rospy.ServiceProxy('/get_pois', CV_POIs)
		self.get_POIs()

		#set initial state
		self.state = 'uninitialized'

	def loop(self):






if __name__ == '__main__':
	rospy.init_node("game_planner")
	GamePlanner()