#!/usr/bin/env python
''' This node provides a python interface to achieve following functions 
based on the move_it python interface.

- getting robot current state
- planning to a pose goal

PUBLISHERS:
    /move_group/display_planned_path (moveit_msgs.msg.DisplayTrajectory) 
        ~ a DisplayTrajectory publisher which is used to display trajectories in Rviz

'''
from __future__ import division
import sys
import copy
import rospy
import moveit_commander
import moveit_msgs.msg
import geometry_msgs.msg
from math import pi
from std_msgs.msg import String
from moveit_commander.conversions import pose_to_list

class MoveGroupPythonInterface(object):
    ''' Integrate the functions we need for the mini-golf project as python interface '''
    def __init__(self):
        ''' Initialize RobotCommander, PlanningSceneInterface and MoveGroupCommander objects respectively '''
        self.robot = moveit_commander.RobotCommander()
        self.scene = moveit_commander.PlanningSceneInterface()
        self.group_name = "right_arm"
        self.move_group = moveit_commander.MoveGroupCommander(self.group_name)
        self.display_trajectory_publisher = rospy.Publisher('/move_group/display_planned_path',
                                               moveit_msgs.msg.DisplayTrajectory,
                                               queue_size=20)
    

    def current_state(self):
        ''' Get the current state of the robot
        
        Returns:
            current_state : current state of the robot
        '''
        current_state = self.robot.get_current_state()
        return current_state


    def go_to_pose(self, position, orientation):
        ''' Make the end effector go to a pose in task space
        
        Args:
            position (1*3 list e.g. [0.4,0.1,0.4]) : x, y, z coordinates of goal position
            orientation (1*4 list e.g. [0,0,0,1]) : x, y, z, w (quaternion) of a orientation
        '''
        pose_goal = geometry_msgs.msg.Pose()
        pose_goal.position.x = position[0]
        pose_goal.position.y = position[1]
        pose_goal.position.z = position[2]
        pose_goal.orientation.x = orientation[0]
        pose_goal.orientation.y = orientation[1]
        pose_goal.orientation.z = orientation[2]
        pose_goal.orientation.w = orientation[3]

        self.move_group.set_pose_target(pose_goal)

        plan = self.move_group.go(wait=True)

        # Calling `stop()` ensures that there is no residual movement
        self.move_group.stop()

        # It is always good to clear your targets after planning with poses.
        # Note: there is no equivalent function for clear_joint_value_targets()
        self.move_group.clear_pose_targets()




if __name__ == '__main__':
    position = [0.4,0.1,0.4]
    orientation = [0,0,0,1]

    moveit_commander.roscpp_initialize(sys.argv)
    rospy.init_node('move_group_python_interface', anonymous=True, log_level=rospy.DEBUG)
    my_sawyer = MoveGroupPythonInterface()
    rospy.loginfo(my_sawyer.current_state())
    my_sawyer.go_to_pose(position,orientation)
    rospy.spin()