#!/usr/bin/env python

import intera_interface
import argparse
import rospy
from mini_golf.srv import DisplayPicture, DisplayPictureResponse

def display_picture(req):
    if req.result == 1:
    	file_arg = "~/msr/fall2019/embedded/final/ws/src/mini_golf/pictures/celebration.png"
    	head_display = intera_interface.HeadDisplay()
    	picture = head_display.display_image(file_arg)#args.file, args.loop, args.rate)
	return DisplayPictureResponse()
    elif req.result == 0:
	file_arg = "~/msr/fall2019/embedded/final/ws/src/mini_golf/pictures/hitting.png"
    	head_display = intera_interface.HeadDisplay()
    	picture = head_display.display_image(file_arg)
	return DisplayPictureResponse()
    elif req.result == 2:
	file_arg = "~/msr/fall2019/embedded/final/ws/src/mini_golf/pictures/upset.png"
    	head_display = intera_interface.HeadDisplay()
    	picture = head_display.display_image(file_arg)
	return DisplayPictureResponse()

def picture_server():
	rospy.init_node("tiger_woods", anonymous=True)
	service = rospy.Service('picture_display', DisplayPicture,display_picture)
	rospy.spin()

if __name__ == '__main__':
    picture_server()


